
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::898843949075:role/terraform-k8s-astounding-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: cam
data:
  redisHost: astounding-redis-cluster.50hq2p.0001.use1.cache.amazonaws.com
  redisUrl: redis://astounding-redis-cluster.50hq2p.0001.use1.cache.amazonaws.com:6379/0


