apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- resources/aws-alb-rbac-role.yml
- resources/alb.yml
- resources/configmaps.yml
- resources/cam-namespace.yml
- resources/camserver.yml
- resources/camworker.yml
- resources/wsserver.yml
- resources/campublisher.yml
- resources/aws-fpga-device-plugin.yml
- resources/ingress.yml

# Enable k8s dashboard
- resources/dashboard.yml
- resources/eks-admin-service-account.yaml

