apiVersion: v1
kind: Pod
metadata:
  name: test-fpga-pod
spec:
  hostNetwork: true
  containers:
  - name: test-fpga-pod
    image: xilinx-ml-suite-ubuntu-16.04-xrt-2018.2-caffe-mls-1.4:latest
    imagePullPolicy: Never
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo hello; sleep 5;done;"]
    resources:
      limits:
        xilinx.com/fpga-xilinx_aws-vu9p-f1-04261818_dynamic_5_0-0: 1
    securityContext:
      privileged: true
    volumeMounts:
    - name: xilinx
      mountPath: /opt/xilinx
  volumes:
  - name: xilinx
    hostPath:
      path: /opt/xilinx
      type: Directory